name: Java Maven Build

on:
  push:
    branches:
      - main  # Ya jo bhi branch tu use karta hai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Apne project ke hisaab se change kar (11, 21, etc.)

      - name: Build with Maven
        run: mvn clean install
